# Generated by Django 3.0.8 on 2020-07-31 03:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('area_unit', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100, verbose_name='type')),
                ('link', models.URLField()),
                ('price', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('tax_value', models.PositiveIntegerField()),
                ('tax_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='last sold price')),
                ('date', models.DateField(auto_now=True, verbose_name='last sold date')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zillow.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('estimate_amount', models.PositiveIntegerField()),
                ('estimate_date', models.DateField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zillow.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_amount', models.PositiveIntegerField()),
                ('estimate_date', models.DateField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zillow.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=100)),
                ('bathrooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('year_build', models.PositiveIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zillow.Listing')),
            ],
        ),
    ]
